/**
 * Nombre de los item
 * @author Ismael Martin Ramirez <br />
 * <a href="https://museumis.github.io/Si/">Web personal</a>
 *
 */
public class Names {

	public static String version = "1.13.2";
	
	public static String[]construccion= {
	
	
			
			
		"stone", 
	    "granite",
	    "polished_granite",
	    "diorite",
	    "polished_diorite",
	    "andesite",
	    "polished_andesite",
	    "grass_block",
	    "dirt",
	    
	    "coarse_dirt",
	    "podzol",
	    "cooblestone",
	    "oak_planks",
	    "spruce_planks",
	    "birch_planks",
	    "jungle_planks",
	    "acacia_planks",
	    "dark_oak_planks",
	    
	    //Bedrock
	    "sand",
	    "red_sand",
	    "gravel",
	    "gold_ore",
	    "iron_ore",
	    "coal_ore",
	    "oak_log",
	    "spruce_log",
	    
	    "birch_log",
	    "jungle_log",
	    "acacia_log",
	    "dark_oak_log",
	    "stripped_oak_log",
	    "stripped_spruce_log",
	    "stripped_birch_log",
	    "stripped_jungle_log",
	    "stripped_acacia_log",
	    
	    "stripped_dark_oak_log",
	    "stripped_oak_wood",
	    "stripped_spruce_wood",
	    "stripped_birch_wood",
	    "stripped_jungle_wood",
	    "stripped_acacia_wood",
	    "stripped_dark_oak_wood",
	    "oak_wood",
	    "spruce_wood",
	    
	    "birch_wood",
	    "jungle_wood",
	    "acacia_wood",
	    "dark_oak_wood",
	    "sponge",
	    "wet_sponge",
	    "glass",
	    "apis_ore",
	    "lapis_block",
	    
	    "sandstone",
	    "chiseled_sandstone",
	    "cut_sandstone",
	    "white_wool",
	    "orange_wool",
	    "magenta_wool",
	    "light_blue_wool",
	    "yellow_wool",
	    "lime_wool",
	    
	    "pink_wool",
	    "gray_wool",
	    "light_gray_wool",
	    "cyan_wool",
	    "purple_wool",
	    "blue_wool",
	    "brown_wool",
	    "green_wool",
	    "red_wool",
	    
	    "black_wool",
	    "gold_block",
	    "iron_block",
	    "oak_slab",
	    "spruce_slab",
	    "birch_slab",
	    "jungle_slab",
	    "acacia_slab",
	    "dark_oak_slab",
	    
	    "stone_slab",
	    "sandstone_slab",
	    "petrified_oak_slab",
	    "cobblestone_slab",
	    "brick_slab",
	    "stone_brick_slab",
	    "nether_brick_slab",
	    "quartz_slab",
	    "red_sandstone_slab",
	    
	    "purpur_slab",
	    "prismarine_slab",
	    "prismarine_brick_slab",
	    "dark_prismarine_slab",
	   // "smooth_quartz",
	   // "smooth_red_sandstone",
	   // "smooth_sandstone",
	   // "smooth_stone",
	    "bricks",
	    
	    "bookshelf",
	    "mossy_cobblestone",
	    "obsidian",
	    "purpur_block",
	    "purpur_pillar",
	    "purpur_stairs",
	    "oak_stairs",
	    "diamond_ore",
	    "diamond_block",
	    
	    "cobblestone_stairs",
	    "redstone_ore",
	    "ice",
	    "snow_block",
	    "clay",
	    "pumpkin",
	    "carved_pumpkin",
	    "netherrack",
	    "soul_sand",
	    	    
	    "glowstone",
	    "jack_o_lantern",
	    "stone_bricks",
	    "mossy_stone_bricks",
	    "cracked_stone_bricks",
	    "chiseled_stone_bricks",
	    "melon",
	    "brick_stairs",
	    "stone_brick_stairs",
	    
	    "mycelium",
	    "nether_bricks",
	    "nether_brick_stairs",
	    "end_stone",
	    "end_stone_bricks",
	    "sandstone_stairs",
	    "emerald_ore",
	    "emerald_block",
	    "spruce_stairs",
	    
	    "birch_stairs",
	    "jungle_stairs",
	    "nether_quartz_ore",
	    "chiseled_quartz_block",
	    "quartz_block",
	    "quartz_pillar",
	    "quartz_stairs",
	    "white_terracotta",	    
	    "orange_terracotta",
	    
	    "magenta_terracotta",
	    "light_blue_terracotta",
	    "yellow_terracotta",
	    "lime_terracotta",	    
	    "pink_terracotta",
	    "gray_terracotta",
	    "light_gray_terracotta",
	    "cyan_terracotta",		    
	    "purple_terracotta",
	    
	    "blue_terracotta",
	    "brown_terracotta",
	    "green_terracotta",
	    "red_terracotta",	    
	    "black_terracotta",
	    "hay_block",
	    "terracotta",
	    "coal_block", 
	    "packed_ice",
	    
	    "acacia_stairs",
	    "dark_oak_stairs",
	    "white_stained_glass",
	    "orange_stained_glass",
	    "magenta_stained_glass",
	    "light_blue_stained_glass",
	    "yellow_stained_glass",
	    "lime_stained_glass",	    
	    "pink_stained_glass",
	    
	    "gray_stained_glass",
	    "light_gray_stained_glass",
	    "cyan_stained_glass",
	    "purple_stained_glass",
	    "blue_stained_glass",
	    "brown_stained_glass",
	    "green_stained_glass",
	    "red_stained_glass",	    
	    "black_stained_glass",	    
	    
	    "prismarine",
	    "prismarine_bricks",
	    "dark_prismarine",
	    "prismarine_stairs",
	    "prismarine_brick_stairs",
	    "dark_prismarine_stairs",
	    "sea_lantern",
	    "red_sandstone",
	    "chiseled_red_sandstone",
	    
	    "cut_red_sandstone",
	    "red_sandstone_stairs",
	    "magma_block",
	    "nether_wart_block",
	    "red_nether_bricks",
	    "bone_block",
	    "white_concrete",
	    "orange_concrete",
	    "magenta_concrete",
	    
	    "light_blue_concrete",
	    "yellow_concrete",
	    "lime_concrete",	    
	    "pink_concrete",
	    "gray_concrete",
	    "light_gray_concrete",
	    "cyan_concrete",
	    "purple_concrete",
	    "blue_concrete",
	    
	    "brown_concrete",
	    "green_concrete",
	    "red_concrete",	    
	    "black_concrete",
	    "white_concrete_powder",
	    "orange_concrete_powder",
	    "magenta_concrete_powder",
	    "light_blue_concrete_powder",
	    "yellow_concrete_powder",
	    
	    "lime_concrete_powder",	    
	    "pink_concrete_powder",
	    "gray_concrete_powder",
	    "light_gray_concrete_powder",
	    "cyan_concrete_powder",
	    "purple_concrete_powder",
	    "blue_concrete_powder",
	    "brown_concrete_powder",
	    "green_concrete_powder",
	    
	    "red_concrete_powder",	    
	    "black_concrete_powder",
	    "dead_tube_coral_block",
	    "dead_brain_coral_block",
	    "dead_bubble_coral_block",
	    "dead_fire_coral_block",
	    "dead_horn_coral_block",
	    "tube_coral_block",
	    "brain_coral_block",
	    
	    "bubble_coral_block",
	    "fire_coral_block",
	    "horn_coral_block",
	    "blue_ice",
	    "dried_kelp_block"
	    
	    
	};
	
	public static String[]decoracion= {			
	    "oak_sapling",
	    "spruce_sapling",
	    "birch_sapling",
	    "jungle_sapling",
	    "acacia_sapling",
	    "dark_oak_sapling",
	    "oak_leaves",
	    "spruce_leaves",
	    "birch_leaves",
	    
	    "jungle_leaves",
	    "acacia_leaves",
	    "dark_oak_leaves",
	    "cobweb",
	    "grass",
	    "fern",
	    "dead_bush",
	    "seagrass",
	    "sea_pickle",
	    
	    "dandelion",
	    "poppy",
	    "blue_orchid",
	    "allium",
	    "azure_bluet",
	    "red_tulip",
	    "orange_tulip",
	    "white_tulip",
	    "pink_tulip",
	    
	    "oxeye_daisy",
	    "brown_mushroom",
	    "red_mushroom",
	    "torch",
	    "end_rod",
	   // "chorus_plant",
	    "chorus_flower",
	    "chest",
	    "crafting_table",
	    
	    //"farmland",
	    "furnace",
	    "ladder",
	    "snow",
	    "cactus",
	    "jukebox",
	    "oak_fence",
	    "spruce_fence",
	    "birch_fence",
	    
	    "jungle_fence",
	    "acacia_fence",
	    "dark_oak_fence",
	    //"infested_stone",
	    //"infested_cobblestone",
	    //"infested_stone_bricks",
	    //"infested_mossy_stone_bricks",
	    //"infested_cracked_stone_bricks",
	    //"infested_chiseled_stone_bricks",
	    
	    "brown_mushroom_block",
	    "red_mushroom_block",
	    //"mushroom_stem",
	    "iron_bars",
	    "glass_pane",
	    "vine",
	    "lily_pad",
	    "nether_brick_fence",
	    "enchanting_table",
	    
	    //"end_portal_frame",
	    "ender_chest",
	    "cobblestone_wall",
	    "mossy_cobblestone_wall",
	    "anvil",
	    //"chipped_anvil",
	    //"damaged_anvil",
	    "white_carpet",
	    "orange_carpet",
	    
	    "magenta_carpet",
	    "light_blue_carpet",
	    "yellow_carpet",
	    "lime_carpet",		    
	    "pink_carpet",
	    "gray_carpet",
	    "light_gray_carpet",
	    "cyan_carpet",
	    "purple_carpet",
	    
	    "blue_carpet",
	    "brown_carpet",
	    "green_carpet",
	    "red_carpet",		    
	    "black_carpet",
	    "slime_block",
	    //"grass_path",
	    "sunflower",
	    "lilac",
	    
	    "rose_bush",
	    "peony",
	    "tall_grass",
	    "large_fern",
	    "white_stained_glass_pane",
	    "orange_stained_glass_pane",
	    "magenta_stained_glass_pane",
	    "light_blue_stained_glass_pane",
	    "yellow_stained_glass_pane",
	    
	    "lime_stained_glass_pane",		    
	    "pink_stained_glass_pane",
	    "gray_stained_glass_pane",
	    "light_gray_stained_glass_pane",
	    "cyan_stained_glass_pane",
	    "purple_stained_glass_pane",
	    "blue_stained_glass_pane",
	    "brown_stained_glass_pane",
	    "green_stained_glass_pane",
	    
	    "red_stained_glass_pane",		    
	    "black_stained_glass_pane",
	    "shulker_box",
	    "white_shulker_box",
	    "orange_shulker_box",
	    "magenta_shulker_box",
	    "light_blue_shulker_box",
	    "yellow_shulker_box",
	    "lime_shulker_box",
	    
	    "pink_shulker_box",
	    "gray_shulker_box",
	    "light_gray_shulker_box",
	    "cyan_shulker_box",
	    "purple_shulker_box",
	    "blue_shulker_box",
	    "brown_shulker_box",
	    "green_shulker_box",
	    "red_shulker_box",
	    
	    "black_shulker_box",
	    "white_glazed_terracotta",
	    "orange_glazed_terracotta",
	    "magenta_glazed_terracotta",
	    "light_blue_glazed_terracotta",
	    "yellow_glazed_terracotta",
	    "lime_glazed_terracotta",		    
	    "pink_glazed_terracotta",
	    "gray_glazed_terracotta",
	    
	    "light_gray_glazed_terracotta",
	    "cyan_glazed_terracotta",
	    "purple_glazed_terracotta",
	    "blue_glazed_terracotta",
	    "brown_glazed_terracotta",
	    "green_glazed_terracotta",
	    "red_glazed_terracotta",		    
	    "black_glazed_terracotta",
	    "tube_coral",
	    
	    "brain_coral",
	    "bubble_coral",
	    "fire_coral",
	    "horn_coral",
	    "dead_brain_coral",
	    "dead_bubble_coral",
	    "dead_fire_coral",
	    "dead_horn_coral",
	    "dead_tube_coral",
	    
	    "tube_coral_fan",
	    "brain_coral_fan",
	    "bubble_coral_fan",
	    "fire_coral_fan",
	    "horn_coral_fan",
	    "dead_tube_coral_fan",
	    "dead_brain_coral_fan",
	    "dead_bubble_coral_fan",
	    "dead_fire_coral_fan",
	    
	    "dead_horn_coral_fan",
	    "painting",
	    "sign",
	    "white_bed",
	    "orange_bed",
	    "magenta_bed",
	    "light_blue_bed",
	    "yellow_bed",
	    "lime_bed",
	    
	    "pink_bed",
	    "gray_bed",
	    "light_gray_bed",
	    "cyan_bed",
	    "purple_bed",
	    "blue_bed",
	    "brown_bed",
	    "green_bed",
	    "red_bed",
	    
	    "black_bed",
	    "item_frame",
	    "flower_pot",
	    "skeleton_skull",
	    "wither_skeleton_skull",
	    //"player_head",
	    "zombie_head",
	    "creeper_head",
	    "dragon_head",
	    
	    "armor_stand",
	    "white_banner",
	    "orange_banner",
	    "magenta_banner",
	    "light_blue_banner",
	    "yellow_banner",
	    "lime_banner",		    
	    "pink_banner",
	    "gray_banner",
	    
	    "light_gray_banner",
	    "cyan_banner",
	    "purple_banner",
	    "blue_banner",
	    "brown_banner",
	    "green_banner",
	    "red_banner",		    
	    "black_banner",		    
	    "end_crystal"
	  
		};

public static String[]redstone= {
			
			
		    "dispenser",
		    "note_block",
		    "sticky_piston",
		    "piston",
		    "tnt",
		    "lever",
		    "stone_pressure_plate",
		    "oak_pressure_plate",
		    "spruce_pressure_plate",
		    
		    "birch_pressure_plate",
		    "jungle_pressure_plate",
		    "acacia_pressure_plate",
		    "dark_oak_pressure_plate",
		    "redstone_torch",
		    "stone_button",
		    "oak_trapdoor",
		    "spruce_trapdoor",
		    "birch_trapdoor",
		    
		    "jungle_trapdoor",
		    "acacia_trapdoor",
		    "dark_oak_trapdoor",
		    "oak_fence_gate",
		    "spruce_fence_gate",
		    "birch_fence_gate",
		    "jungle_fence_gate",
		    "acacia_fence_gate",
		    "dark_oak_fence_gate",
		    
		    "redstone_lamp",
		    "tripwire_hook",
		    "oak_button",
		    "spruce_button",
		    "birch_button",
		    "jungle_button",
		    "acacia_button",
		    "dark_oak_button",
		    "trapped_chest",
		    
		    "light_weighted_pressure_plate",
		    "heavy_weighted_pressure_plate",
		    "daylight_detector",
		    "redstone_block",
		    "hopper",
		    "dropper",
		    "iron_trapdoor",
		    "observer",
		    "iron_door",
		    
		    "oak_door",
		    "spruce_door",
		    "birch_door",
		    "jungle_door",
		    "acacia_door",
		    "dark_oak_door",
		    "repeater",
		    "comparator",
		    "redstone"
		};

public static String[]transporte= {
		
	    "powered_rail",
	    "detector_rail",
	    "powered_rail",
	    "detector_rail",
	    "rail",
	    "activator_rail",
	    "minecart",
	    "saddle",
	    "oak_boat",
	    "chest_minecart",
	    "furnace_minecart",
	    
	    "carrot_on_a_stick",
	    "tnt_minecart",
	    "hopper_minecart",
	    "elytra",
	    "spruce_boat",
	    "birch_boat",
	    "jungle_boat",
	    "acacia_boat",
	    "dark_oak_boat"
	};

public static String[]objetosvarios= {
		
	
		
		"beacon",
	    "turtle_egg",
	    "conduit",
	    "scute",
	    "coal",
	    "charcoal",
	    "diamond",
	    "iron_ingot",
	    "gold_ingot",

	    "stick",
	    "bowl",
	    "string",
	    "feather",
	    "gunpowder",
	    "wheat_seeds",
	    "wheat",
	    "flint",
	    "bucket",
	    
	    "water_bucket",
	    "lava_bucket",
	    "snowball",
	    "leather",
	    "milk_bucket",
	    "pufferfish_bucket",
	    "salmon_bucket",
	    "cod_bucket",
	    "tropical_fish_bucket",	    
	    
	    "brick",
	    "clay_ball",
	    "sugar_cane",
	    "kelp",
	    "paper",
	    "book",
	    "smile_ball",
	    "egg",
	    "glowstone_dust",
	    
	    "ink_sac",
	    "rose_red",
	    "cactus_green",
	    "cocoa_beans",
	    "lapis_lazuli",
	    "purple_dye",
	    "cyan_dye",
	    "light_gray_dye",
	    "gray_dye",
	    
	    "pink_dye",
	    "lime_dye",
	    "dandelion_yellow",
	    "light_blue_dye",
	    "magenta_dye",
	    "orange_dye",
	    "bone_meal",
	    "bone",
	    "sugar",
	    	    
	    "pumpkin_seeds",
	    "melon_seeds",
	    "ender_pearl",
	    "blaze_rod",
	    "gold_nugget",
	    "nether_wart",
	    "ender_eye",
	    //"eggs"
	    //"eggs",
	    
	    //"eggs",
	    //"eggs",
	    //"eggs",
	    "experience_bottle",
	    "fire_charge",
	    "writable_book",
	    "emerald",
	    "map",
	    
	    
	    "nether_star",
	    "firework_rocket",
	    "firework_star",
	    "nether_brick",
	    "quartz",
	    "prismarine_shard",
	    "prismarine_crystals",
	    "rabbit_hide",
	    "iron_horse_armor",
	    
	    "golden_horse_armor",
	    "diamond_horse_armor",
	    "chorus_fruit",
	    "popped_chorus_fruit",
	    "beetroot_seeds",
	    "shulker_shell",
	    "iron_nugget",
	    "music_disc_13",
	    "music_disc_cat",
	    
	    "music_disc_blocks",
	    "music_disc_chirp",
	    "music_disc_far",
	    "music_disc_mall",
	    "music_disc_mellohi",
	    "music_disc_stal",
	    "music_disc_strad",
	    "music_disc_warp",
	    "music_disc_11",
	   
	    "music_disc_wait",
	    "nautilus_shell",
	    "heart_of_the_sea"
		
};

public static String[]alimentacion= {
		
	    "apple",
	    "mushroom_stew",
	    "bread",
	    "porkchop",
	    "cooked_porkchop",
	    "golden_apple",
	    "enchanted_golden_apple",
	    "cod",
	    "salmon",
	    
	    "tropical_fish",
	    "pufferfish",
	    "cooked_cod",
	    "cooked_slmon",
	    "cake",
	    "cookie",
	    "melon_slice",
	    "dried_kelp",
	    "bee121f",
	    
	    "cooked_beef",
	    "chicken",
	    "cooked_chicken",
	    "rotten_flesh",
	    "spider_eye",
	    "carrot",
	    "potato",
	    "baked_potato",
	    "poisonous_potato",
	    
	    "pumpkin_pie",
	    "rabbit",
	    "cooked_rabbit",
	    "rabbit_stew",
	    "mutton",
	    "cooked_mutton",
	    "beetroot",
	    "beetroot_soup"

	};

public static String[]herramientas= {
		"iron_shovel",
		"iron_pickaxe",
		"iron_axe",
		"flint_and_steel",
		"wooden_shovel",
		"wooden_pickaxe",
		"wooden_axe",
		"stone_shovel",
		"stone_pickase",
		
		"stone_axe",
		"diamond_shovel",
		"diamond_picka",
		"qxe",
		"diamond_axe",
		"golden_shovel",
		"golden_pickaxe",
		"golden_axe",
		"wooden_hoe",
		"stone_hoe",
		
		"iron_hoe",
		"diamond_hoe",
		"golden_hoe",
		"compass",
		"fishing_rod",
		"clock",
		"shears",
		
		"lead",
		"name_tag"
		

	};

public static String[]combate= {
		
	    "turtle_helmet",
	    "bow",
	    "arrow",
	    "iron_sword",
	    "wooden_sword",
	    "stone_sword",
	    "diamond_sword",
	    "golden_sword",
	    "leather_helmet",
	    
	    "leather_chestplate",
	    "leather_leggings",
	    "leather_boots",
	    "chainmail_helmet",
	    "chainmail_chestplate",
	    "chai1nmail_leggings",
	    "chainmail_boots",
	    "iron_helmet",
	    "iron_chestplate",
	    
	    "iron_leggings",
	    "iron_boots",
	    "diamond_helmet",
	    "diamond_chestplate",
	    "diamond_leggings",
	    "diamond_boots",		
	    "golden_helmet",
	    "golden_chestplate",
	    "golden_leggings",
	    
	    "golden_boots",
	    "spectral_arrow",
	    "shield",
	    "totem_of_undying",
	    "trident"
	    	    
};

public static String[]pociones= {
		
	    "ghast_tear",
	    "ghast_tear",
	    "glass_bottle",
	    "fermented_spider_eye",
	    
	    "blaze_powder",
	    "magma_cream",
	    "brewing_stand",
	    "cauldron",
	    "glistering_melon_slice",
	    "golden_carrot",
	    "rabbit_foot",
	    "dragon_breath",
	    "phantom_membrane",
	    
	    "water_breathing"
	    
	};

public static String[]librosEncantados = {
		
		"efficiency-5",		
		"silk_touch-1",		
		"unbreaking-3",	
		"efficiency-5",
		"fortune-3",
		"luck_of_the_sea-3",
		"lure-3",
		"mending-1",
		"vanishing_curse-1",
		
		
		"protection-4",
		"fire_protection-4",
		"feather_falling-4",
		"blast_protection-4",
		"projectile_protection-4",
		"respiration-3",
		"aqua_affinity-1",
		"thorns-3",

		"depth_strider-3",
		"frost_walker-2",
		"binding_curse-1",
		"sharpness-5",
		"smite-5",
		"bane_of_arthropods-5",
		"knockback-2",
		"fire_aspect-2",
		"looting-3",

		"sweeping-3",

		"power-5",
		"punch-2",
		"flame-1",
		"infinity-1",
		"loyalty-3",
		"impaling-5",   
		"riptide-3",

		 "channeling-1"
	
		
};

public static String[]pocimas = {
		"water",
		"mundane",
		"thick",
		"awkward",
		"night_vision", 
		"long_night_vision",
		"invisibility",
		"long_invisibility",
		"leaping",  
		"strong_leaping",  
		"long_leaping",
		"fire_resistance", 
		"long_fire_resistance",
		"swiftness",  
		"strong_swiftness",  
		"long_swiftness",
		"slowness", 
		"strong_slowness", 
		"long_slowness",
		"water_breathing",  
		"long_water_breathing",
		"healing",  
		"strong_healing",
		"harming", 
		"strong_harming",
		"poison", 
		"strong_poison", 
		"long_poison",
		"regeneration",
		"strong_regeneration",
		"long_regeneration",
		"strength",  
		"strong_strength", 
		"long_strength",
		"weakness", 
		"long_weakness",
		"turtle_master", 
		"strong_turtle_master", 
		"long_turtle_master",
		"slow_falling", 
		"long_slow_falling"
		
};

public static String[]flechasencantadas = {
		"tipped_arrow"
};
}
